### ISSUE TITLE
SyntaxError: Unexpected reserved word "await"

### ISSUE THREAD

**Issue by CaptainPhilipp** [laverdet/screeps-steamless-client#11]
```
npx screeps-steamless-client

file:///usr/local/lib/node_modules/screeps-steamless-client/dist/index.js:49
const [data, stat] = await async function () {
                     ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

**Comment by CaptainPhilipp** [comment]
Fix: ```nvm install node
