### ISSUE TITLE
Unexpected identifier import os from 'os';

### ISSUE THREAD

**Issue by FutureAstroMiner** [laverdet/screeps-steamless-client#9]
I am getting an error when trying to run npx after running npm install -g screeps-steamless-client.

$ npx screeps-steamless-client
/usr/local/lib/node_modules/screeps-steamless-client/dist/index.js:2
import os from 'os';
       ^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by MiguelBamberino** [comment]
works on node 18 too.
